# Numpy进阶

## Numpy数组操作

### 添加元素
numpy.append()函数可以在数组的末尾添加元素。它接受两个参数：要添加元素的数组和要添加的元素。
>注意事项:
- numpy.append()函数会返回一个新的数组，而不是修改原始数组。
- 维度必须匹配，否则会引发错误。二维数组只能添加二维数组，三维数组只能添加三维数组，以此类推。

In [1]:
import numpy as np

In [2]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
data1 = np.append([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12]], axis=0)
data1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
data2 = np.append([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10], [11], [12]], axis=1)
data2

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

### 插入元素
np.insert()函数可以在指定位置插入元素。它接受三个参数：要插入元素的数组、要插入的位置和要插入的元素。
>注意事项:
- np.insert()函数会返回一个新的数组，而不是修改原始数组。
- 维度必须匹配，否则会引发错误。二维数组只能插入二维数组，三维数组只能插入三维数组，以此类推。

In [5]:
arr1 = np.random.randint(1, 10, 5)
arr1

array([9, 2, 8, 4, 3])

In [6]:
np.insert(arr1, 2, 99) 

array([ 9,  2, 99,  8,  4,  3])

In [7]:
arr2 = np.random.randint(1, 10, size=(4, 3))
arr2

array([[6, 9, 7],
       [4, 1, 6],
       [5, 3, 9],
       [2, 8, 7]])

In [8]:
# 插入行
np.insert(arr2,2, [[99, 99, 99]], axis=0)

array([[ 6,  9,  7],
       [ 4,  1,  6],
       [99, 99, 99],
       [ 5,  3,  9],
       [ 2,  8,  7]])

In [9]:
# 插入列
np.insert(arr2, 1, [[99]], axis=1)

array([[ 6, 99,  9,  7],
       [ 4, 99,  1,  6],
       [ 5, 99,  3,  9],
       [ 2, 99,  8,  7]])

### 删除元素
numpy.delete()函数可以删除指定位置的元素。它接受两个参数：要删除元素的数组和要删除的位置。
>注意事项:
- numpy.delete()函数会返回一个新的数组，而不是修改原始数组。
- 维度必须匹配，否则会引发错误。二维数组只能删除二维数组，三维数组只能删除三维数组，以此类推。

In [10]:
arr1

array([9, 2, 8, 4, 3])

In [11]:
np.delete(arr1, 2)

array([9, 2, 4, 3])

In [12]:
arr2

array([[6, 9, 7],
       [4, 1, 6],
       [5, 3, 9],
       [2, 8, 7]])

In [13]:
# 删除行
np.delete(arr2, 1, axis=0)

array([[6, 9, 7],
       [5, 3, 9],
       [2, 8, 7]])

In [14]:
np.delete(arr2, [0, 1],axis=0)

array([[5, 3, 9],
       [2, 8, 7]])

### 数组变形reshape
numpy.reshape()函数可以在不改变数据的情况下改变数组的形状。
格式: numpy.reshape(a, newshape, order='C')
- a: 要改变形状的数组。
- newshape: 新的形状，可以是一个整数或一个整数元组。
- order: 可选参数，指定读取元素的顺序。'C'表示按行读取，'F'表示按列读取，'A'表示按照内存中的顺序读取，‘K’表示按照元素在内存中的顺序读取。
>注意事项:
- numpy.reshape()函数会返回一个新的数组，而不是修改原始数组。
- 新的形状必须与原始数组的元素数量相同，否则会引发错误。

In [15]:
arr1 = np.random.randint(1, 10, 10)
arr1

array([4, 5, 5, 8, 8, 2, 1, 1, 8, 3])

In [16]:
np.reshape(arr1, shape = (5, 2), order='C')

array([[4, 5],
       [5, 8],
       [8, 2],
       [1, 1],
       [8, 3]])

In [17]:
np.reshape(arr1, (5, 2), order='F')

array([[4, 2],
       [5, 1],
       [5, 1],
       [8, 8],
       [8, 3]])

### 数组迭代器
numpy.ndarray.flat属性返回一个迭代器，可以用来遍历数组中的元素。它以一维的方式访问数组中的元素，无论数组的维度是多少。
>注意事项:
- numpy.ndarray.flat属性返回一个迭代器，而不是一个数组。
- 迭代器会按照数组的元素在内存中的顺序访问元素，无论数组的维度是多少。

In [18]:
arr1

array([4, 5, 5, 8, 8, 2, 1, 1, 8, 3])

In [19]:
for element in arr1.flat:
    print(element)

4
5
5
8
8
2
1
1
8
3


In [20]:
arr2

array([[6, 9, 7],
       [4, 1, 6],
       [5, 3, 9],
       [2, 8, 7]])

In [21]:
for element in arr2.flat:
    print(element)

6
9
7
4
1
6
5
3
9
2
8
7


### 数组扁平处理
numpy.ndarray.flatten()方法可以将多维数组转换为一维数组。它返回一个新的数组，而不是修改原始数组。
>注意事项:
- numpy.ndarray.flatten()方法会返回一个新的数组，而不是修改原始数组。
- 该方法会按照行优先的顺序将元素展平，即先按行访问元素，然后按列访问元素。
numpy.ravel()函数也可以将多维数组转换为一维数组，但它返回的是一个视图，而不是一个新的数组。
>注意事项:
- numpy.ravel()函数返回的是一个视图，而不是一个新的数组。这意味着修改ravel()返回的数组会修改原始数组。
- 该函数会按照行优先的顺序将元素展平，即先按行访问元素，然后按列访问元素。

In [22]:
arr2.flatten()

array([6, 9, 7, 4, 1, 6, 5, 3, 9, 2, 8, 7])

In [23]:
arr2_1 = arr2.ravel()
arr2_1

array([6, 9, 7, 4, 1, 6, 5, 3, 9, 2, 8, 7])

In [24]:
arr2_1[0] = 99

In [25]:
arr2

array([[99,  9,  7],
       [ 4,  1,  6],
       [ 5,  3,  9],
       [ 2,  8,  7]])

### 数组翻转(矩阵转置)
numpy.transpose()函数可以翻转数组的维度。它接受一个参数：要翻转的数组。
>注意事项:
- numpy.transpose()函数会返回一个新的数组，而不是修改原始数组。
- 该函数会按照指定的轴顺序翻转数组的维度，默认情况下会将所有轴翻转。

In [26]:
arr2

array([[99,  9,  7],
       [ 4,  1,  6],
       [ 5,  3,  9],
       [ 2,  8,  7]])

In [27]:
np.transpose(arr2)

array([[99,  4,  5,  2],
       [ 9,  1,  3,  8],
       [ 7,  6,  9,  7]])