# Numpy进阶

## Numpy数组操作

### 添加元素
numpy.append()函数可以在数组的末尾添加元素。它接受两个参数：要添加元素的数组和要添加的元素。
>注意事项:
- numpy.append()函数会返回一个新的数组，而不是修改原始数组。
- 维度必须匹配，否则会引发错误。二维数组只能添加二维数组，三维数组只能添加三维数组，以此类推。

In [1]:
import numpy as np

In [2]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
data1 = np.append(data, [[10, 11, 12]], axis=0)
data1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
data2 = np.append([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10], [11], [12]], axis=1)
data2

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

### 插入元素
np.insert()函数可以在指定位置插入元素。它接受三个参数：要插入元素的数组、要插入的位置和要插入的元素。
>注意事项:
- np.insert()函数会返回一个新的数组，而不是修改原始数组。
- 维度必须匹配，否则会引发错误。二维数组只能插入二维数组，三维数组只能插入三维数组，以此类推。

In [5]:
arr1 = np.random.randint(1, 10, 5)
arr1

array([3, 6, 3, 5, 2])

In [6]:
np.insert(arr1, 2, 99) 

array([ 3,  6, 99,  3,  5,  2])

In [7]:
arr2 = np.random.randint(1, 10, size=(4, 3))
arr2

array([[5, 6, 5],
       [6, 8, 7],
       [2, 4, 3],
       [5, 2, 6]])

In [8]:
# 插入行
np.insert(arr2,2, [[99, 99, 99]], axis=0)

array([[ 5,  6,  5],
       [ 6,  8,  7],
       [99, 99, 99],
       [ 2,  4,  3],
       [ 5,  2,  6]])

In [9]:
# 插入列
np.insert(arr2, 1, [[99]], axis=1)
# 原数组 arr2 有 3 行，而你只提供了一个 [[99]]。NumPy 发现高度不够（只有 1 行），于是广播机制启动。它自动把 [[99]] 向下复制拉伸 3 遍，变成了 [[99, 99, 99], [99, 99, 99], [99, 99, 99]]，这样就满足了插入行的要求。

array([[ 5, 99,  6,  5],
       [ 6, 99,  8,  7],
       [ 2, 99,  4,  3],
       [ 5, 99,  2,  6]])

### 删除元素
numpy.delete()函数可以删除指定位置的元素。它接受两个参数：要删除元素的数组和要删除的位置。
>注意事项:
- numpy.delete()函数会返回一个新的数组，而不是修改原始数组。
- 维度必须匹配，否则会引发错误。二维数组只能删除二维数组，三维数组只能删除三维数组，以此类推。

In [10]:
arr1

array([3, 6, 3, 5, 2])

In [11]:
np.delete(arr1, 2)

array([3, 6, 5, 2])

In [12]:
arr2

array([[5, 6, 5],
       [6, 8, 7],
       [2, 4, 3],
       [5, 2, 6]])

In [13]:
# 删除行
np.delete(arr2, 1, axis=0)

array([[5, 6, 5],
       [2, 4, 3],
       [5, 2, 6]])

In [14]:
np.delete(arr2, [0, 1],axis=0)

array([[2, 4, 3],
       [5, 2, 6]])

### 数组变形reshape
numpy.reshape()函数可以在不改变数据的情况下改变数组的形状。
格式: numpy.reshape(a, newshape, order='C')
- a: 要改变形状的数组。
- newshape: 新的形状，可以是一个整数或一个整数元组。
- order: 可选参数，指定读取元素的顺序。'C'表示按行读取，'F'表示按列读取，'A'表示按照内存中的顺序读取，‘K’表示按照元素在内存中的顺序读取。默认值为'C'。
>注意事项:
- numpy.reshape()函数会返回一个新的数组，而不是修改原始数组。
- 新的形状必须与原始数组的元素数量相同，否则会引发错误。

In [15]:
arr1 = np.random.randint(1, 10, 10)
arr1

array([3, 1, 2, 8, 6, 9, 2, 9, 1, 9])

In [16]:
np.reshape(arr1, shape = (5, 2), order='C')

array([[3, 1],
       [2, 8],
       [6, 9],
       [2, 9],
       [1, 9]])

In [17]:
np.reshape(arr1, (5, 2), order='F')

array([[3, 9],
       [1, 2],
       [2, 9],
       [8, 1],
       [6, 9]])

### 数组迭代器
numpy.ndarray.flat属性返回一个迭代器，可以用来遍历数组中的元素。它以一维的方式访问数组中的元素，无论数组的维度是多少。
>注意事项:
- numpy.ndarray.flat属性返回一个迭代器，而不是一个数组。
- 迭代器会按照数组的元素顺序返回元素，无论数组的维度是多少。

In [18]:
arr1

array([3, 1, 2, 8, 6, 9, 2, 9, 1, 9])

In [19]:
for element in arr1.flat:
    print(element)

3
1
2
8
6
9
2
9
1
9


In [20]:
arr2

array([[5, 6, 5],
       [6, 8, 7],
       [2, 4, 3],
       [5, 2, 6]])

In [21]:
for element in arr2.flat:
    print(element)

5
6
5
6
8
7
2
4
3
5
2
6


### 数组扁平处理
numpy.ndarray.flatten()方法可以将多维数组转换为一维数组。它返回一个新的数组，而不是修改原始数组。
>注意事项:
- numpy.ndarray.flatten()方法会返回一个新的数组，而不是修改原始数组。
- 该方法会按照行优先的顺序将元素展平，即先按行访问元素，然后按列访问元素。   

numpy.ravel()函数也可以将多维数组转换为一维数组，但它返回的是一个视图，而不是一个新的数组。
>注意事项:
- numpy.ravel()函数返回的是一个视图，而不是一个新的数组。这意味着修改ravel()返回的数组也会修改原始数组。
- 该函数会按照行优先的顺序将元素展平，即先按行访问元素，然后按列访问元素。

In [22]:
arr2.flatten()

array([5, 6, 5, 6, 8, 7, 2, 4, 3, 5, 2, 6])

In [23]:
arr2_1 = arr2.ravel()
arr2_1

array([5, 6, 5, 6, 8, 7, 2, 4, 3, 5, 2, 6])

In [24]:
arr2_1[0] = 99

In [25]:
arr2

array([[99,  6,  5],
       [ 6,  8,  7],
       [ 2,  4,  3],
       [ 5,  2,  6]])

### 数组翻转(矩阵转置)
numpy.transpose()函数可以翻转数组的维度。它接受一个参数：要翻转的数组。
>注意事项:
- numpy.transpose()函数会返回一个新的数组，而不是修改原始数组。
- 该函数会按照指定的轴顺序翻转数组的维度，默认情况下会将所有轴翻转。

In [26]:
arr2

array([[99,  6,  5],
       [ 6,  8,  7],
       [ 2,  4,  3],
       [ 5,  2,  6]])

In [27]:
np.transpose(arr2)

array([[99,  6,  2,  5],
       [ 6,  8,  4,  2],
       [ 5,  7,  3,  6]])

## Numpy数字函数

### 三角函数
#### 正弦函数
np.sin()
#### 余弦函数
np.cos()
#### 正切函数
np.tan()
#### 接收的参数是弧度

In [36]:
# 生成-π 到 π 之间的随机数
data = np.random.random(10)*2*np.pi-np.pi

In [37]:
np.sin(data)

array([-0.97439449,  0.1918597 ,  0.57870091, -0.85283105, -0.99439432,
        0.76642859,  0.5372793 , -0.7967581 , -0.38334272, -0.93832016])

In [38]:
np.sin(np.pi / 2)

np.float64(1.0)

### 舍入函数
#### np.around(a, decimals=0).   
参数说明:   
a: 输入数组.   
decimals: 要保留的小数位数，默认为0。  

In [41]:
np.around(np.random.random(10), decimals=3)

array([0.802, 0.934, 0.876, 0.156, 0.875, 0.374, 0.78 , 0.099, 0.663,
       0.698])

### 算数函数
#### np.add(x1, x2):求和
#### np.subtract(x1, x2):求差
#### np.multiply(x1, x2):求积
#### np.divide(x1, x2):求商
#### np.power(x1, x2):求幂
#### np.mod(x1, x2):求模
#### np.log(x):求自然对数

In [42]:
a1 = np.random.randint(1, 10, 5)
a2 = np.random.randint(1, 10, 5)
display(a1, a2)

array([6, 7, 4, 1, 9])

array([2, 3, 7, 4, 3])

In [43]:
np.add(a1, a2)

array([ 8, 10, 11,  5, 12])

In [45]:
b1 = np.random.randint(1, 10, (5,3))
b2 = np.random.randint(1, 10, 3)
display(b1, b2)

array([[2, 3, 8],
       [6, 3, 7],
       [1, 7, 6],
       [3, 6, 7],
       [4, 4, 3]])

array([9, 4, 1])

In [46]:
np.add(b1, b2)

array([[11,  7,  9],
       [15,  7,  8],
       [10, 11,  7],
       [12, 10,  8],
       [13,  8,  4]])

In [48]:
data = np.random.randint(1, 10, 5)
display(data)

array([3, 5, 3, 4, 6])

In [49]:
np.power(data,2)

array([ 9, 25,  9, 16, 36])

In [52]:
np.power(data,0.5)

array([1.73205081, 2.23606798, 1.73205081, 2.        , 2.44948974])

In [53]:
np.mod(data,3)

array([0, 2, 0, 1, 0])

In [56]:
np.log10(100)

np.float64(2.0)

In [57]:
np.log10(data)

array([0.47712125, 0.69897   , 0.47712125, 0.60205999, 0.77815125])

### Numpy查找和排序

#### 查找索引
- np.argmax()函数返回数组中最大值的索引。   
- np.argmin()函数返回数组中最小值的索引。

In [58]:
data = np.random.randint(1, 100, 10)
data

array([90, 18, 93,  3, 20, 38, 36, 61, 33, 43])

In [59]:
np.argmax(data)

np.int64(2)

### 条件查找
- np.where()函数可以根据条件返回满足条件的元素的索引或元素本身。它接受三个参数：条件、满足条件时返回的值和不满足条件时返回的值。

np.where(condition, x, y)函数的参数说明:
- condition: 一个布尔数组，表示条件。就是一个条件表达式。
- x: 满足条件时返回的值，可以是一个数组或一个标量。
- y: 不满足条件时返回的值，可以是一个数组或一个标量。  

In [63]:
data

array([90, 18, 93,  3, 20, 38, 36, 61, 33, 43])

In [64]:
np.where(data > 50) # 返回满足条件的元素的索引

(array([0, 2, 7]),)

In [65]:
np.where(data > 50, data, -1)# 返回满足条件的元素本身，不满足条件的元素用 -1 替代

array([90, -1, 93, -1, -1, -1, -1, 61, -1, -1])

### 快速排序
- np.sort()函数可以对数组进行排序。它接受一个参数：要排序的数组。
- ndarray.sort()方法可以对数组进行排序。它会修改原始数组，而不是返回一个新的数组。
>注意事项:
- np.sort()函数会返回一个新的数组，而不是修改原始数组。
- 该函数会按照默认的升序对数组进行排序，可以通过参数指定排序的轴和排序的顺序。

In [67]:
data

array([90, 18, 93,  3, 20, 38, 36, 61, 33, 43])

In [68]:
np.sort(data)

array([ 3, 18, 20, 33, 36, 38, 43, 61, 90, 93])

In [69]:
data

array([90, 18, 93,  3, 20, 38, 36, 61, 33, 43])

In [70]:
data.sort() # 原地排序，修改原数组
data

array([ 3, 18, 20, 33, 36, 38, 43, 61, 90, 93])

### 索引排序
- np.argsort()函数返回数组元素排序后的索引。它接受一个参数：要排序的数组。

In [72]:
data = np.random.randint(1, 100, 10)

In [73]:
data

array([64, 90, 17, 14, 63, 24, 14, 96,  9, 45])

In [75]:
np.argsort(data)

array([8, 3, 6, 2, 5, 9, 4, 0, 1, 7])

### 部分排序
- np.partition(a,k)函数可以对数组进行部分排序。它接受两个参数：要排序的数组和要排序的元素的索引。
>注意事项:
- np.partition()函数会返回一个新的数组，而不是修改原始数组。
- 该函数会将数组分成两部分，前k个元素是数组中最小的k个元素，后面的元素是数组中剩余的元素，但它们的顺序不保证。
> np.partition()函数的参数说明:
- a: 要排序的数组。
- k: 要排序的元素的索引，可以是一个整数或一个整数数组。

In [76]:
data

array([64, 90, 17, 14, 63, 24, 14, 96,  9, 45])

In [ ]:
np.partition(data, 5)# 返回一个新的数组，前5个元素是数组中最小的5个元素，后面的元素是数组中剩余的元素，但它们的顺序不保证

array([14, 14,  9, 17, 24, 45, 63, 96, 90, 64])

In [80]:
np.partition(data, -2) # 返回一个新的数组，前5个元素是数组中剩余的元素，后面的元素是数组中最大的5个元素，但它们的顺序不保证

array([14, 45, 17, 14,  9, 24, 63, 64, 90, 96])